version: "3"
services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD:-1234}"
        ports:
            - 27018:27017
        volumes:
            - mongodb_data_container:/data/db

    goldybot:
        image: devgoldy/goldybot
        environment:
            DISCORD_TOKEN: "${DISCORD_TOKEN}"
            MONGODB_URL: "mongodb://root:${MONGODB_PASSWORD:-1234}@mongodb:27017/"

            WAIT_HOSTS: "mongodb:27017"
            WAIT_HOSTS_TIMEOUT: 60
        volumes:
            - ${GOLDY_DIRECTORY}:/app/goldy

volumes:
    mongodb_data_container: